server:
  port: 8761  
  
spring:
  application:
    name: eureka-server
  security:
   basic:
    enabled: true               # 开启基于HTTP basic的认证
   user:
    name: user                  # 配置登录的账号是user
    password: 123       # 配置登录的密码是password123
    
logging:
  config: classpath:log4j2.xml
  level:
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN
    com.netflix: WARN
    
eureka:
  instance:
    hostname: my-eureka
    preferIpAddress: false
    metadataMap.zone: zone1
    appname: ${spring.application.name}
  client:
    # 注册中心将自己作为客户端来尝试注册自己，注册中心集群环境下需开启此配置
    register-with-eureka: false
     # 检索服务选项，注册中心不需要检索服务
    fetch-registry: false
    region: chn
    #availability-zones:
    #  chn: zone1,zone2
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka/
      #zone1: http://user:123@192.168.2.44:8761/eureka/,http://user:123@192.168.2.45:8761/eureka/
      #zone2: http://user:123@192.168.2.46:8761/eureka/
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 30
    disable-delta: true
  instance-info-replication-interval-seconds: 24
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
    peer-node-read-timeout-ms: 5000
    evictionIntervalTimerInMs: 4000
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
    health:
      sensitive: false
  server:
    port: 8001